create database Hospital 

use Hospital

--Crear tablas y llaves
CREATE TABLE HOSPITALES(HOSPITAL_COD INT,NOMBRE VARCHAR(15),DIRECCION VARCHAR(20),TELEFONO CHAR(8),NUM_CAMA INT,
CONSTRAINT HOSPITAL_PK PRIMARY KEY (HOSPITAL_COD));

CREATE TABLE SALA(HOSPITAL_COD INT NOT NULL,SALA_COD INT,NOMBRE VARCHAR(20),NUM_CAMA INT,
CONSTRAINT SALA_PK PRIMARY KEY (SALA_COD),CONSTRAINT HOSPITAL_SALA_FK FOREIGN KEY (HOSPITAL_COD) REFERENCES HOSPITALES (HOSPITAL_COD));

CREATE TABLE PLANTILLA(HOSPITAL_COD INT NOT NULL,SALA_COD INT NOT NULL,EMPLEADO_NO INT,APELLIDO VARCHAR(15),FUNCION CHAR(10),
TURNO CHAR (1) ,SALARIO INT,
CONSTRAINT EMPLEADO_PK PRIMARY KEY (EMPLEADO_NO),
CONSTRAINT HOSPITAL_FK FOREIGN KEY (HOSPITAL_COD) REFERENCES HOSPITALES (HOSPITAL_COD),
CONSTRAINT SALA_FK FOREIGN KEY (SALA_COD) REFERENCES SALA (SALA_COD),
CONSTRAINT TURNO_CH CHECK (TURNO IN ('T','M','N')),
CONSTRAINT SALARIO_CH CHECK (SALARIO > 0));

CREATE TABLE ENFERMO(INSCRIPCION INT,APELLIDO VARCHAR(15),DIRECCION VARCHAR(20),FECHA_NAC DATE,S VARCHAR(1),NSS INT,
CONSTRAINT ENFERMO_PK PRIMARY KEY (INSCRIPCION));

CREATE TABLE OCUPACION(INSCRIPCION INT PRIMARY KEY,HOSPITAL_COD INT ,SALA_COD INT,CAMA INT,
CONSTRAINT HOSPITAL_OCUP_FK FOREIGN KEY (HOSPITAL_COD) REFERENCES HOSPITALES (HOSPITAL_COD),
CONSTRAINT SALA_OCUP_FK FOREIGN KEY (SALA_COD) REFERENCES SALA (SALA_COD));

-------> Consultas <----------

SELECT * FROM HOSPITALES
SELECT * FROM SALA
select * FROM ENFERMO
SELECT * FROM OCUPACION
select * from PLANTILLA

--1.Listado de todos los miembros del personal cuyo nombre empiece por la letra 'A'
SELECT * FROM PLANTILLA WHERE APELLIDO LIKE 'A%'
